In [1]:
import numpy as np


In [2]:
#create new 2D array
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [5]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [6]:
#agerigate function


#find min value of array
arr1.min()

1

In [8]:
#find max value of array
arr1.max()

9

In [9]:
#find mean value of array
arr1.mean()

5.0

In [10]:
#argmin / argmax function


In [12]:
#argmin
# it return the position of the max value in array 
arr1.argmax()

8

In [13]:
# it return the position of min value in the array
arr1.argmin()

0

In [15]:
#to sort the values in the array 
arr1.sort()
arr1
# and it sort the data in the row vise 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# argsort

In [16]:
arr1.argsort()
#it agve the index value of all the value in row form

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [17]:
arr2=np.array([[[1,2,3],[3,2,1]]])
arr2

array([[[1, 2, 3],
        [3, 2, 1]]])

In [19]:
arr2.ndim

3

In [25]:
arr2[0][1][1]

2