In [13]:
#identity matrix
#transpose
#
#2D data 3*3 matrix
import numpy as np
arr=np.array([[34,20,31],[11,22,3],[14,25,73]])
arr

array([[34, 20, 31],
       [11, 22,  3],
       [14, 25, 73]])

In [8]:
arr.ndim

2

In [14]:
#transpose
arr.T

array([[34, 11, 14],
       [20, 22, 25],
       [31,  3, 73]])

In [10]:
#identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
#aggregation function


In [15]:
arr


array([[34, 20, 31],
       [11, 22,  3],
       [14, 25, 73]])

In [16]:
arr.min()

3

In [17]:
arr.mean()

25.88888888888889

In [19]:
arr.max()

73

# argmax/argmin

In [20]:
arr

array([[34, 20, 31],
       [11, 22,  3],
       [14, 25, 73]])

In [22]:
#it denote the position of max value
arr.argmax()

8

In [23]:
#it denote the position of min value
arr.argmin()

5

In [27]:
arr.sort()
arr
#it sort data coloum vise

array([[20, 31, 34],
       [ 3, 11, 22],
       [14, 25, 73]])

In [29]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)