In [2]:
#wap to print 3Dmetrix
import numpy as np
arr1=np.array([[[1,67,3],[1,56,3],[67,2,3]]])
arr1

array([[[ 1, 67,  3],
        [ 1, 56,  3],
        [67,  2,  3]]])

In [27]:
arr1[0]

array([[ 1, 67,  3],
       [ 1, 56,  3],
       [67,  2,  3]])

In [28]:
# useing slising with indexing in array
arr1[0][0]

array([ 1, 67,  3])

In [29]:
arr1[0][0][0]

1

In [30]:
arr1[0][0][1]

67

In [31]:
a=np.array([1,2,3])
a[1]

2

In [32]:
arr1[0][1][1]

56

In [34]:
#sum
a=arr1.sum()
a

203

In [39]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a=arr.sum(1)
a

array([[12, 15, 18]])

In [40]:
a=arr.sum(axis=[0][])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr3=np.array([[1,2,3],[1,2,3],[1,2,3]])
arr3


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [45]:
arr3.shape

(4, 4)

In [46]:
arr3.size

16

In [49]:
#zeros and ones
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [50]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [51]:
#arange funcion
np.arange(6,61,2)

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38,
       40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [52]:
np.arange(1,61)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [53]:
np.arange(61)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [54]:
#empty
#linespace
np.empty(2)

array([ 8.22612418e-134, -7.58425513e+010])

In [55]:
#to create rendom data
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [58]:
#to create 2d array data
np.empty((6,6))

array([[1.27048199e-311, 1.27048199e-311, 1.27048146e-311,
        1.27049983e-311, 1.27049921e-311, 1.27049921e-311],
       [1.27047405e-311, 1.27049921e-311, 1.27049981e-311,
        1.27047405e-311, 1.27052810e-311, 1.27047405e-311],
       [1.27049982e-311, 1.27049979e-311, 1.27047441e-311,
        1.27047405e-311, 1.27047407e-311, 1.27047405e-311],
       [1.27047405e-311, 1.27049741e-311, 1.27047389e-311,
        1.27047405e-311, 1.27049982e-311, 1.27049820e-311],
       [1.27049742e-311, 1.27049981e-311, 1.27047405e-311,
        1.27049981e-311, 1.27047405e-311, 1.27049753e-311],
       [1.27049819e-311, 1.27049753e-311, 1.27049819e-311,
        1.27052844e-311, 1.27047407e-311, 1.27047405e-311]])

In [4]:
#linspace is used to get data between two number first argument denote to starting point, secound argument denote to last point
#and third arument denote the number of data create in a list.
np.linspace(1,10,60)

array([ 1.        ,  1.15254237,  1.30508475,  1.45762712,  1.61016949,
        1.76271186,  1.91525424,  2.06779661,  2.22033898,  2.37288136,
        2.52542373,  2.6779661 ,  2.83050847,  2.98305085,  3.13559322,
        3.28813559,  3.44067797,  3.59322034,  3.74576271,  3.89830508,
        4.05084746,  4.20338983,  4.3559322 ,  4.50847458,  4.66101695,
        4.81355932,  4.96610169,  5.11864407,  5.27118644,  5.42372881,
        5.57627119,  5.72881356,  5.88135593,  6.03389831,  6.18644068,
        6.33898305,  6.49152542,  6.6440678 ,  6.79661017,  6.94915254,
        7.10169492,  7.25423729,  7.40677966,  7.55932203,  7.71186441,
        7.86440678,  8.01694915,  8.16949153,  8.3220339 ,  8.47457627,
        8.62711864,  8.77966102,  8.93220339,  9.08474576,  9.23728814,
        9.38983051,  9.54237288,  9.69491525,  9.84745763, 10.        ])

In [68]:
x1=[23,45,89,34]
x2=[78,86,45,23]
for i in x1:
    for j in x2:
        if i==j:
            print(i)

23
45
