In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.size

5

In [7]:
arr.shape

(5,)

In [10]:
#2D metrix
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
arr1.shape

(2, 5)

In [12]:
arr1.size

10

In [16]:
#3D metrix
arr2=np.array([[[1,2,3,],[4,5,6],[7,8,9]]])
arr2


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
arr2.shape

(1, 3, 3)

In [18]:
arr2.size

9