In [2]:
import numpy as np
x=np.array([[23,90,40],[64,3,45]])

In [3]:
x

array([[23, 90, 40],
       [64,  3, 45]])

# different type of function used in numpy

In [5]:
#sum accoding to colume
x.sum(0)

array([87, 93, 85])

In [6]:
#sum accoding to row
x.sum(1)

array([153, 112])

In [7]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.empty((12,12))

array([[            nan, 0.00000000e+000, 7.10742016e-312,
        7.10716415e-312, 0.00000000e+000,             nan,
                    nan, 0.00000000e+000, 1.51005560e-207,
        0.00000000e+000, 4.44659081e-323, 7.10742016e-312],
       [7.10716418e-312,             nan, 0.00000000e+000,
                    nan, 0.00000000e+000, 7.08746594e-312,
        3.55727265e-322, 5.43472210e-323, 7.10742016e-312,
        7.10716418e-312, 0.00000000e+000, 1.38338381e-322],
       [            nan, 0.00000000e+000, 7.08746594e-312,
        7.11454530e-322, 5.43472210e-323, 7.10742016e-312,
        7.10716418e-312,             nan, 1.48219694e-322,
                    nan, 0.00000000e+000, 7.08746594e-312],
       [1.06718180e-321, 5.43472210e-323, 7.10742016e-312,
        7.10716419e-312, 7.10688483e-312, 1.28457068e-322,
                    nan, 0.00000000e+000, 7.08746594e-312,
        1.42290906e-321, 5.43472210e-323, 7.10742016e-312],
       [7.10716417e-312, 7.10688483e-312, 7.90505033

In [15]:
np.linspace(1,15)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [18]:
np.linspace(1,6,20)

array([1.        , 1.26315789, 1.52631579, 1.78947368, 2.05263158,
       2.31578947, 2.57894737, 2.84210526, 3.10526316, 3.36842105,
       3.63157895, 3.89473684, 4.15789474, 4.42105263, 4.68421053,
       4.94736842, 5.21052632, 5.47368421, 5.73684211, 6.        ])

In [19]:
#arange
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])