In [1]:
import numpy as np


In [11]:
#create 1D array using numpy
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [12]:
arr.shape

(3,)

In [13]:
arr.size

3

In [14]:
arr.ndim

1

In [43]:
#create 2D array using numpy

arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr1.shape

(3, 3)

In [4]:
arr1.ndim

2

In [5]:
arr1.size

9

In [16]:
#create 3D array using numpy
arr2=np.array([[[11,12,13],[14,15,16],[17,18,19]]])
arr2

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [8]:
arr2.shape

(1, 3, 3)

In [9]:
arr2.size

9

In [10]:
arr2.ndim

3

In [17]:
arr2[0]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [20]:
arr2[0][0]

array([11, 12, 13])

In [24]:
arr2[0][0][0]

11

In [36]:
arr2[0:2][0][2]

array([17, 18, 19])

In [38]:
arr2[0][0][2]

13

In [40]:
arr.sum()

6

In [44]:
arr1.sum()

45

In [42]:
arr2.sum()

135

In [49]:
#sum all element in the row
arr2.sum(2)

array([[36, 45, 54]])

In [50]:
#sum all element in a colum
arr2.sum(1)


array([[42, 45, 48]])

In [55]:
#to create array of 1's
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [56]:
#to create array of 0's
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [57]:
#to create 1D array from starting and ending point
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [59]:
# to create 1D array from starting and ending point and have a distance b/w
# 2 item.
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [64]:
# to create 1D array for rendom value upt to 12 element
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [65]:
#to create 2D array for rendom value using empty
# you need to notice number of [] for dimention of the array
np.empty((6,6))

array([[ 0.00000000e+000,  6.95332168e-310,  1.28457068e-321,
                     nan,  1.63352819e-301,  3.82599592e-297],
       [ 7.46699393e-301,  2.50789587e-292,  1.86989321e-306,
         1.07775123e-282,  1.34047036e-272,  1.63380945e-301],
       [ 2.10053204e-301,  5.16385263e-297,  1.63380945e-301,
         7.46699209e-301,  1.22545320e-301,  4.90181799e-296],
       [ 8.78323363e-268,  2.10053208e-301,  3.28971468e-287,
         1.98731873e-263,  3.77352449e-258,  1.07147996e-296],
       [ 1.11436016e-306,  1.30191895e-258,  2.55898978e-306,
         1.56002683e-307,  1.60013415e-309,  1.62069717e-248],
       [ 2.38707768e-253,  5.12939350e-307,  9.51983029e-292,
        -2.02715626e+243,  1.39069238e-309,  4.23936054e-307]])

In [70]:
#linespace is used to create rendom data from one starting point to end point 
# and we can create n number of values as per user input
np.linspace(1,10,600)

array([ 1.        ,  1.01502504,  1.03005008,  1.04507513,  1.06010017,
        1.07512521,  1.09015025,  1.10517529,  1.12020033,  1.13522538,
        1.15025042,  1.16527546,  1.1803005 ,  1.19532554,  1.21035058,
        1.22537563,  1.24040067,  1.25542571,  1.27045075,  1.28547579,
        1.30050083,  1.31552588,  1.33055092,  1.34557596,  1.360601  ,
        1.37562604,  1.39065109,  1.40567613,  1.42070117,  1.43572621,
        1.45075125,  1.46577629,  1.48080134,  1.49582638,  1.51085142,
        1.52587646,  1.5409015 ,  1.55592654,  1.57095159,  1.58597663,
        1.60100167,  1.61602671,  1.63105175,  1.64607679,  1.66110184,
        1.67612688,  1.69115192,  1.70617696,  1.721202  ,  1.73622705,
        1.75125209,  1.76627713,  1.78130217,  1.79632721,  1.81135225,
        1.8263773 ,  1.84140234,  1.85642738,  1.87145242,  1.88647746,
        1.9015025 ,  1.91652755,  1.93155259,  1.94657763,  1.96160267,
        1.97662771,  1.99165275,  2.0066778 ,  2.02170284,  2.03